### ISSUE TITLE
How can I dump DBFs to CSVs faster?

### ISSUE THREAD

**Issue by marklit** [yellowfeather/dbf2csv#2]
I recently benchmarked dbf2csv against a Python-based combination of dbfread and Pandas and found I could dump DBFs to CSVs 21x faster with dbf2csv. I reported the performance difference to the dbfread project (the ticket can be seen here https://github.com/olemb/dbfread/issues/38).

The DBF would have sat in the page cache but nonetheless represented 1,489 MB of data read. The resulting CSV represented 638 MB. So this works out to 20 MB/s read and 8.6 MB/s written.

I was using Boost v1.58.0 and gcc 5.4.0. These were my compilation flags I used:

```
$ cmake -DCMAKE_CXX_FLAGS="-m64 -DHAVE_HIDDEN -DHAVE_BUILTIN_CTZL -DMEDIUM_STRATEGY -DX86_64 -DX86_NOCHECK_SSE2 -DUNALIGNED_OK -DUNROLL_LESS -DX86_CPUID -DX86_SSE2_FILL_WINDOW -DX86_SSE4_2_CRC_HASH -DX86_PCLMULQDQ_CRC -DX86_QUICK_STRATEGY" . # -O3 in CMakeLists.txt
```

Are there any compilation flags or any other steps I could take to improve the speed of dbf2csv?

**Comment by chrisrichards** [comment]
I don't think there will be any quick wins to speed it up. It maybe possible to get some speed improvements by benchmarking and optimising the code but it's not really something I have time to do at the moment I'm afraid.
